version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ../db:/var/lib/mysql
    restart: always
    # expose:
    # - "3306"
    ports: 
     - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
     - ../OcuKdelWeb:/var/www/html/wp-content/themes/OcuKdelWeb
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db #mysqlサービス名を指定
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ../phpmyadmin/sessions:/sessions
volumes:
    db_data: